name: GregGorman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08745
title: Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfe'
    - '#6c5437'
    - '#191112'
    - '#f2bf80'
    - '#fd3e3f'
  brandStrength: 0
  lightness: 0.012127090711146593
  saturation: 1
  rhythmicContrast: 0
purpose: []
