name: GregGorman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08745
title: Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcd8d3'
    - '#304554'
    - '#fdb482'
    - '#0c0000'
    - '#926e31'
  brandStrength: 0
  lightness: 0.012127090711146593
  saturation: 1
  rhythmicContrast: 0
purpose: []
